# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Roberto Moreno
tagline:          Software Developer
description:      Learning & playing in the JDK environment.
baseurl:          /
url:			  http://robertomoreno.github.io

author:
  name:           Roberto Moreno
  linkedin:            https://es.linkedin.com/in/robertomorenoperez
  email:          pmrebor@gmail.com
  github: 		  https://github.com/robertomoreno
  twitter:		  https://twitter.com/rorerez

  
paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/robertomoreno/robertomoreno.github.io.git
