# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Roberto Moreno
tagline:          Software Developer
description:      Learning & playing in the JDK environment.
baseurl:          /
url:			  https://robertomoreno.github.io

author:
  name:           Roberto Moreno
  linkedin:       https://es.linkedin.com/in/robertomorenoperez
  email:          pmrebor@gmail.com
  github: 		  https://github.com/robertomoreno
  twitter:
    url:          https://twitter.com/rorerez
    name:         rorerez
  disqus:
    id:           disqus_aFgecu356n

  
paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/robertomoreno/robertomoreno.github.io.git
