# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Roberto Moreno
tagline:          Software Developer
description:      Learning & playing in the JDK environment.
url:              http://robertomoreno.github.io
baseurl:          /

author:
  name:           Roberto Moreno
  url:            https://es.linkedin.com/in/robertomorenoperez
  mail:           pmrebor@gmail.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/robertomoreno/robertomoreno.github.io.git
